spring:
    profiles.active: db-rds


---


spring:
    profiles: db-h2
    datasource:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    jackson:
        time-zone: Asia/Seoul
debug: true
server:
    port: 8080